==========================================================================
# üìÅ **ATIVIDADE FIAP - Global Solution**
==========================================================================

**Autor.....:** Diego Nunes Veiga

**RM........:** 560658

**Turma...:** Gradua√ß√£o - 1TIAOR

**Data......:** 01/06/2025

==========================================================================

In [ ]:
# Importa√ß√£o das bibliotecas
import warnings
import os
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error,mean_squared_error
from sklearn.cluster import KMeans, DBSCAN

## ‚Ü™ **DESASTRE - Vale do Itaja√≠ 2008**

**M√™s do ocorrido:** Novembro

**Data do ocorrido:** N/A

### **Leitura dos dados**

In [ ]:
# === Leitura dos dados de entrada ===

input_2008 = [
    "INMET_S_SC_A841_JOACABA_01-01-2008_A_31-12-2008.xlsx",
    "INMET_S_SC_A860_CURITIBANOS_28-02-2008_A_31-12-2008.xlsx",
    "INMET_S_SC_A861_RIO DO CAMPO_10-03-2008_A_31-12-2008.xlsx",
    "INMET_S_SC_A863_ITUPORANGA_04-03-2008_A_31-12-2008.xlsx"
    ]

output_2008 = []

In [ ]:
# === Designa√ß√£o do m√™s de desastre ===

# M√™s com desastre no formato (ano, m√™s)
meses_com_desastre = [(2008, 11)]
meses_interesse = [(2008,10),(2008, 11)]

In [ ]:
# === Formata√ß√£o dos dados ===

for arquivo in input_2008:

  # L√™ os metadados para obter a cidade
  df_cidade = pd.read_excel(arquivo, nrows=8)
  cidade = df_cidade.iloc[1, 1]

  # L√™ os dados ignorando os metadados
  df_dados = pd.read_excel(arquivo, skiprows=8)

  # Adiciona a cidade em todos os registros
  df_dados["CIDADE"] = cidade

  # Converte a coluna de data para datetime (essencial para comparar ano e m√™s)
  df_dados['DATA (YYYY-MM-DD)'] = pd.to_datetime(df_dados['DATA (YYYY-MM-DD)'])

  # Filtra apenas os dados nas datas de interesse
  df_dados = df_dados[
      df_dados['DATA (YYYY-MM-DD)'].apply(lambda d: (d.year, d.month) in meses_interesse)]

  # Marca como 1 o valor de desastre para datas que est√£o nos meses indicados
  df_dados['DESASTRE'] = df_dados['DATA (YYYY-MM-DD)'].apply(
      lambda d: 1 if (d.year, d.month) in meses_com_desastre else 0
      )

  # Salva o resultado final
  output_2008.append(df_dados)

## ‚Ü™ **DESASTRE - Blumenau 2023**

**M√™s do ocorrido:** Novembro

**Data do ocorrido:** N/A

### **Leitura dos dados**

In [ ]:
# === Leitura dos dados de entrada ===

input_2023 = [
    "INMET_S_SC_A862_RIO NEGRINHO_01-01-2023_A_31-12-2023.xlsx",
    "INMET_S_SC_A863_ITUPORANGA_01-01-2023_A_31-12-2023.xlsx",
    "INMET_S_SC_A817_INDAIAL_01-01-2023_A_31-12-2023.xlsx",
    ]

output_2023 = []

In [ ]:
# === Designa√ß√£o do m√™s de desastre ===

# M√™s com desastre no formato (ano, m√™s)
meses_com_desastre = [(2023, 11)]
meses_interesse = [(2023,10),(2023, 11)]

In [ ]:
# === Formata√ß√£o dos dados ===

for arquivo in input_2023:

  # L√™ os metadados para obter a cidade
  df_cidade = pd.read_excel(arquivo, nrows=8)
  cidade = df_cidade.iloc[1, 1]

  # L√™ os dados ignorando os metadados
  df_dados = pd.read_excel(arquivo, skiprows=8)

  # Padroniza o nome da coluna de data
  df_dados.rename(columns={"Data": "DATA (YYYY-MM-DD)"}, inplace=True)

  # Converte a coluna de data
  df_dados['DATA (YYYY-MM-DD)'] = pd.to_datetime(df_dados['DATA (YYYY-MM-DD)'])

  # Adiciona a cidade
  df_dados["CIDADE"] = cidade

  # Filtra apenas os dados nas datas de interesse
  df_dados = df_dados[
      df_dados['DATA (YYYY-MM-DD)'].apply(lambda d: (d.year, d.month) in meses_interesse)]

  # Marca como desastre os meses definidos
  df_dados['DESASTRE'] = df_dados['DATA (YYYY-MM-DD)'].apply(
      lambda d: 1 if (d.year, d.month) in meses_com_desastre else 0
  )

  # Adiciona na lista final
  output_2023.append(df_dados)

## ‚Ü™ **DESASTRE - Rio Grande do Sul 2024**

**M√™s do ocorrido:** Abril e Maio

**Data do ocorrido:** N/A

### **Leitura dos dados**

In [ ]:
# === Leitura dos dados de entrada ===

input_2024 = [
    "INMET_S_RS_A801_PORTO ALEGRE - JARDIM BOTANICO_01-01-2024_A_31-12-2024.xlsx",
    "INMET_S_RS_A879_CANELA_01-01-2024_A_31-12-2024.xlsx",
    "INMET_S_RS_A880_VACARIA_01-01-2024_A_31-12-2024.xlsx",
    "INMET_S_RS_A893_ENCRUZILHADA DO SUL_01-01-2024_A_31-12-2024.xlsx",
    "INMET_S_RS_A894_SERAFINA CORREA_01-01-2024_A_31-12-2024.xlsx",
    "INMET_S_RS_B807_PORTO ALEGRE- BELEM NOVO_01-01-2024_A_31-12-2024.xlsx"
]

output_2024 = []

In [ ]:
# === Designa√ß√£o do m√™s de desastre ===

# M√™s com desastre no formato (ano, m√™s)
meses_com_desastre = [(2024, 4),(2024, 5)]
meses_interesse = [(2024, 3),(2024, 4),(2024, 5)]

In [ ]:
# === Formata√ß√£o dos dados ===

for arquivo in input_2024:

  # L√™ os metadados para obter a cidade
  df_cidade = pd.read_excel(arquivo, nrows=8)
  cidade = df_cidade.iloc[1, 1]

  # L√™ os dados ignorando os metadados
  df_dados = pd.read_excel(arquivo, skiprows=8)

  # Padroniza o nome da coluna de data
  df_dados.rename(columns={"Data": "DATA (YYYY-MM-DD)"}, inplace=True)

  # Converte a coluna de data
  df_dados['DATA (YYYY-MM-DD)'] = pd.to_datetime(df_dados['DATA (YYYY-MM-DD)'])

  # Adiciona a cidade
  df_dados["CIDADE"] = cidade

  # Filtra apenas os dados nas datas de interesse
  df_dados = df_dados[
      df_dados['DATA (YYYY-MM-DD)'].apply(lambda d: (d.year, d.month) in meses_interesse)]

  # Marca como desastre os meses definidos
  df_dados['DESASTRE'] = df_dados['DATA (YYYY-MM-DD)'].apply(
      lambda d: 1 if (d.year, d.month) in meses_com_desastre else 0
  )

  # Adiciona na lista final
  output_2024.append(df_dados)

## ‚Ü™ **CONCATENANDO OS DADOS**

### **Transforma√ß√£o na tabela base**

In [ ]:
# Concatena todos os DataFrames das listas em um √∫nico DataFrame
dados_unificados = pd.concat(output_2008 + output_2023 + output_2024, ignore_index=True)

In [ ]:
# Apresenta√ß√£o dos dados Resultantes

dados_unificados.info()
print('\n')
dados_unificados.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23496 entries, 0 to 23495
Data columns (total 23 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   DATA (YYYY-MM-DD)                                      23496 non-null  datetime64[ns]
 1   HORA (UTC)                                             5856 non-null   object
 2   PRECIPITA√á√ÉO TOTAL, HOR√ÅRIO (mm)                       20994 non-null  float64
 3   PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  20994 non-null  float64
 4   PRESS√ÉO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)        20962 non-null  float64
 5   PRESS√ÉO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)       20962 non-null  float64
 6   RADIACAO GLOBAL (KJ/m¬≤)                                5856 non-null   float64
 7   TEMPERATURA DO AR - BULBO SECO, HORARIA (¬∞C)           20994 non-null  float64
 8   TEMPERATURA DO PONTO DE ORVALHO (¬∞C)                   20957 non-null  float64
 9   TEMPERATURA M√ÅXIMA NA HORA ANT. (AUT) (¬∞C)             20962 non-null  float64
 10  TEMPERATURA M√çNIMA NA HORA ANT. (AUT) (¬∞C)             20962 non-null  float64
 11  TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (¬∞C)       20924 non-null  float64
 12  TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (¬∞C)       20923 non-null  float64
 13  UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)               20926 non-null  float64
 14  UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)               20925 non-null  float64
 15  UMIDADE RELATIVA DO AR, HORARIA (%)                    20957 non-null  float64
 16  VENTO, DIRE√á√ÉO HORARIA (gr) (¬∞ (gr))                   20651 non-null  float64
 17  VENTO, RAJADA MAXIMA (m/s)                             20560 non-null  float64
 18  VENTO, VELOCIDADE HORARIA (m/s)                        20644 non-null  float64
 19  CIDADE                                                 23496 non-null  object
 20  DESASTRE                                               23496 non-null  int64
 21  Hora UTC                                               17640 non-null  object
 22  RADIACAO GLOBAL (Kj/m¬≤)                                9654 non-null   float64
dtypes: datetime64[ns](1), float64(18), int64(1), object(3)
memory usage: 4.1+ MB

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITA√á√ÉO TOTAL, HOR√ÅRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESS√ÉO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESS√ÉO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m¬≤),"TEMPERATURA DO AR - BULBO SECO, HORARIA (¬∞C)",TEMPERATURA DO PONTO DE ORVALHO (¬∞C),TEMPERATURA M√ÅXIMA NA HORA ANT. (AUT) (¬∞C),...,UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIRE√á√ÉO HORARIA (gr) (¬∞ (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",CIDADE,DESASTRE,Hora UTC,RADIACAO GLOBAL (Kj/m¬≤)
0,2008-10-01,00:00:00,0.0,926.4,926.5,926.2,-9999.0,18.0,14.5,18.5,...,81.0,78.0,80.0,2.0,1.3,0.3,JOACABA,0,NaN,NaN
1,2008-10-01,01:00:00,0.0,926.6,926.6,926.3,-9999.0,17.4,14.3,18.1,...,82.0,80.0,82.0,55.0,2.8,2.0,JOACABA,0,NaN,NaN
2,2008-10-01,02:00:00,0.0,926.2,926.6,926.2,-9999.0,16.6,13.8,17.4,...,83.0,82.0,83.0,48.0,4.1,1.8,JOACABA,0,NaN,NaN
3,2008-10-01,03:00:00,0.0,926.0,926.3,926.0,-9999.0,15.9,13.3,16.6,...,85.0,83.0,85.0,57.0,5.1,3.2,JOACABA,0,NaN,NaN
4,2008-10-01,04:00:00,0.0,925.5,926.0,925.4,-9999.0,15.2,13.0,16.0,...,87.0,85.0,87.0,50.0,5.1,2.9,JOACABA,0,NaN,NaN

In [ ]:

dados_unificados = dados_unificados.rename(columns={
    'DATA (YYYY-MM-DD)' :                                         "Data (YYYY-MM-DD)",
    'HORA (UTC)':                                                 "Hora (UTC)",
    'PRECIPITA√á√ÉO TOTAL, HOR√ÅRIO (mm)':                           "Precipitacao (mm)",
    'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)':      "Press√£o Atmosf√©rica (mB)",
    'PRESS√ÉO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)':            "Press√£o M√°xima (mB)",
    'PRESS√ÉO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)':           "Press√£o M√≠nima (mB)",
    'RADIACAO GLOBAL (KJ/m¬≤)':                                    "Radiacao Global (KJ/m¬≤)",
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (¬∞C)':               "Temperatura do Ar (¬∞C)",
    'TEMPERATURA DO PONTO DE ORVALHO (¬∞C)':                       "Ponto de Orvalho (¬∞C)",
    'TEMPERATURA M√çNIMA NA HORA ANT. (AUT) (¬∞C)':                 "Temperatura M√≠nima (¬∞C)",
    'TEMPERATURA M√ÅXIMA NA HORA ANT. (AUT) (¬∞C)':                 "Temperatura M√°xima (¬∞C)",
    'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (¬∞C)':           "Temperatura Orvalho M√°xima (¬∞C)",
    'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (¬∞C)':           "Temperatura Orvalho M√≠nima (¬∞C)",
    'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)':                   "Umidade M√°xima (%)",
    'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)':                   "Umidade M√≠nima (%)",
    'UMIDADE RELATIVA DO AR, HORARIA (%)':                        "Umidade Relativa (%)",
    'VENTO, DIRE√á√ÉO HORARIA (gr) (¬∞ (gr))':                       "Dire√ß√£o Vento (¬∞)",
    'VENTO, RAJADA MAXIMA (m/s)':                                 "Vento m√°ximo (m/s)",
    'VENTO, VELOCIDADE HORARIA (m/s)':                            "Vento hora (m/s)",
    'DESASTRE':                                                   "Desastre Natural",
    'CIDADE':                                                     "Cidade",
    'Hora UTC':                                                   "Hora UTC",
    'RADIACAO GLOBAL (Kj/m¬≤)':                                    "Radia√ß√£o Clobal (Kj/m¬≤)"
})

In [ ]:
# Apresenta√ß√£o dos dados Resultantes

dados_unificados.info()
dados_unificados.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23496 entries, 0 to 23495
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Data (YYYY-MM-DD)                23496 non-null  datetime64[ns]
 1   Hora (UTC)                       5856 non-null   object
 2   Precipitacao (mm)                20994 non-null  float64
 3   Press√£o Atmosf√©rica (mB)         20994 non-null  float64
 4   Press√£o M√°xima (mB)              20962 non-null  float64
 5   Press√£o M√≠nima (mB)              20962 non-null  float64
 6   Radiacao Global (KJ/m¬≤)          5856 non-null   float64
 7   Temperatura do Ar (¬∞C)           20994 non-null  float64
 8   Ponto de Orvalho (¬∞C)            20957 non-null  float64
 9   Temperatura M√°xima (¬∞C)          20962 non-null  float64
 10  Temperatura M√≠nima (¬∞C)          20962 non-null  float64
 11  Temperatura Orvalho M√°xima (¬∞C)  20924 non-null  float64
 12  Temperatura Orvalho M√≠nima (¬∞C)  20923 non-null  float64
 13  Umidade M√°xima (%)               20926 non-null  float64
 14  Umidade M√≠nima (%)               20925 non-null  float64
 15  Umidade Relativa (%)             20957 non-null  float64
 16  Dire√ß√£o Vento (¬∞)                20651 non-null  float64
 17  Vento m√°ximo (m/s)               20560 non-null  float64
 18  Vento hora (m/s)                 20644 non-null  float64
 19  Cidade                           23496 non-null  object
 20  Desastre Natural                 23496 non-null  int64
 21  Hora UTC                         17640 non-null  object
 22  Radia√ß√£o Clobal (Kj/m¬≤)          9654 non-null   float64
dtypes: datetime64[ns](1), float64(18), int64(1), object(3)
memory usage: 4.1+ MB

,Data (YYYY-MM-DD),Hora (UTC),Precipitacao (mm),Press√£o Atmosf√©rica (mB),Press√£o M√°xima (mB),Press√£o M√≠nima (mB),Radiacao Global (KJ/m¬≤),Temperatura do Ar (¬∞C),Ponto de Orvalho (¬∞C),Temperatura M√°xima (¬∞C),...,Umidade M√°xima (%),Umidade M√≠nima (%),Umidade Relativa (%),Dire√ß√£o Vento (¬∞),Vento m√°ximo (m/s),Vento hora (m/s),Cidade,Desastre Natural,Hora UTC,Radia√ß√£o Clobal (Kj/m¬≤)
0,2008-10-01,00:00:00,0.0,926.4,926.5,926.2,-9999.0,18.0,14.5,18.5,...,81.0,78.0,80.0,2.0,1.3,0.3,JOACABA,0,NaN,NaN
1,2008-10-01,01:00:00,0.0,926.6,926.6,926.3,-9999.0,17.4,14.3,18.1,...,82.0,80.0,82.0,55.0,2.8,2.0,JOACABA,0,NaN,NaN
2,2008-10-01,02:00:00,0.0,926.2,926.6,926.2,-9999.0,16.6,13.8,17.4,...,83.0,82.0,83.0,48.0,4.1,1.8,JOACABA,0,NaN,NaN
3,2008-10-01,03:00:00,0.0,926.0,926.3,926.0,-9999.0,15.9,13.3,16.6,...,85.0,83.0,85.0,57.0,5.1,3.2,JOACABA,0,NaN,NaN
4,2008-10-01,04:00:00,0.0,925.5,926.0,925.4,-9999.0,15.2,13.0,16.0,...,87.0,85.0,87.0,50.0,5.1,2.9,JOACABA,0,NaN,NaN

In [ ]:
# Salva em um √∫nico arquivo Excel
dados_unificados.to_excel("Base_Unificada_INMET.xlsx", index=False)

print("Todos os dados foram concatenados e salvos como 'Base_Unificada_INMET.xlsx'")

Todos os dados foram concatenados e salvos como 'Base_Unificada_INMET.xlsx'